FROM python:3.10
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY api ./api
COPY ui ./ui
COPY preprocess.py .
COPY model ./model
ENV PYTHONPATH=/app
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
